collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.5017921
color:
  saturation: 0.04301075
  brandStrength: 1
  rhythmicContrast: 1
  brandColors:
    - '#E0D9D7'
    - '#4B1F1F'
    - '#884A39'
    - '#ACACB4'
    - '#66656D'
  lightness: 1
layout_spectrum: 0.6577061
name: Amadeus
